# Generated by Django 6.0.4 on 2026-05-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_catalog_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_categor_6b96c3_idx',
            old_name='products_pr_ca_avail_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_feature_8a6f84_idx',
            old_name='products_pr_feat_c_at_idx',
        ),
        migrations.RenameIndex(
            model_name='productreview',
            new_name='products_pr_product_153dad_idx',
            old_name='products_prev_prod_mod_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='products_pr_product_06fb37_idx',
            old_name='products_pv_prod_sz_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
